# JWT signing secret. Generated by Terraform and stored in Secret Manager; the
# Cloud Run service reads it as the JWT_SECRET env var.
#
# NOTE: the generated value also lives in Terraform state (see backend.tf) —
# keep the state bucket access-controlled.
resource "random_password" "jwt" {
  length  = 48
  special = true
}

resource "google_secret_manager_secret" "jwt" {
  secret_id = "jwt-secret"

  replication {
    auto {}
  }

  # Block accidental destroys; deliberate teardown removes this first.
  lifecycle {
    prevent_destroy = true
  }

  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "jwt" {
  secret      = google_secret_manager_secret.jwt.id
  secret_data = random_password.jwt.result
}
